// Generated by cpp11: do not edit by hand
// clang-format off

#include "tinystring_types.h"
#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// r_alphabet.cpp
cpp11::writable::strings rcpp_alphabet(const TinyStrings_ptr& x_ptr);
extern "C" SEXP _tinystring_rcpp_alphabet(SEXP x_ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(rcpp_alphabet(cpp11::as_cpp<cpp11::decay_t<const TinyStrings_ptr&>>(x_ptr)));
  END_CPP11
}
// r_flatten.cpp
TinyStrings_ptr rcpp_flatten(const TinyStrings_ptr& x_ptr, const cpp11::strings & collapse);
extern "C" SEXP _tinystring_rcpp_flatten(SEXP x_ptr, SEXP collapse) {
  BEGIN_CPP11
    return cpp11::as_sexp(rcpp_flatten(cpp11::as_cpp<cpp11::decay_t<const TinyStrings_ptr&>>(x_ptr), cpp11::as_cpp<cpp11::decay_t<const cpp11::strings &>>(collapse)));
  END_CPP11
}
// r_length.cpp
cpp11::writable::integers rcpp_length(const TinyStrings_ptr& x_ptr);
extern "C" SEXP _tinystring_rcpp_length(SEXP x_ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(rcpp_length(cpp11::as_cpp<cpp11::decay_t<const TinyStrings_ptr&>>(x_ptr)));
  END_CPP11
}
// r_length.cpp
std::size_t rcpp_num_strings(const TinyStrings_ptr& x_ptr);
extern "C" SEXP _tinystring_rcpp_num_strings(SEXP x_ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(rcpp_num_strings(cpp11::as_cpp<cpp11::decay_t<const TinyStrings_ptr&>>(x_ptr)));
  END_CPP11
}
// r_length.cpp
TinyStrings_ptr rcpp_set_length(const TinyStrings_ptr& x_ptr, const int size);
extern "C" SEXP _tinystring_rcpp_set_length(SEXP x_ptr, SEXP size) {
  BEGIN_CPP11
    return cpp11::as_sexp(rcpp_set_length(cpp11::as_cpp<cpp11::decay_t<const TinyStrings_ptr&>>(x_ptr), cpp11::as_cpp<cpp11::decay_t<const int>>(size)));
  END_CPP11
}
// r_pack.cpp
TinyStrings_ptr rcpp_pack(const cpp11::strings & x, const cpp11::strings & alphabet);
extern "C" SEXP _tinystring_rcpp_pack(SEXP x, SEXP alphabet) {
  BEGIN_CPP11
    return cpp11::as_sexp(rcpp_pack(cpp11::as_cpp<cpp11::decay_t<const cpp11::strings &>>(x), cpp11::as_cpp<cpp11::decay_t<const cpp11::strings &>>(alphabet)));
  END_CPP11
}
// r_recode.cpp
TinyStrings_ptr rcpp_recode(const TinyStrings_ptr& x_ptr, const cpp11::list_of<cpp11::strings> & recodes);
extern "C" SEXP _tinystring_rcpp_recode(SEXP x_ptr, SEXP recodes) {
  BEGIN_CPP11
    return cpp11::as_sexp(rcpp_recode(cpp11::as_cpp<cpp11::decay_t<const TinyStrings_ptr&>>(x_ptr), cpp11::as_cpp<cpp11::decay_t<const cpp11::list_of<cpp11::strings> &>>(recodes)));
  END_CPP11
}
// r_recode.cpp
TinyStrings_ptr rcpp_ip_recode(const TinyStrings_ptr& x_ptr, const cpp11::list_of<cpp11::strings> & recodes);
extern "C" SEXP _tinystring_rcpp_ip_recode(SEXP x_ptr, SEXP recodes) {
  BEGIN_CPP11
    return cpp11::as_sexp(rcpp_ip_recode(cpp11::as_cpp<cpp11::decay_t<const TinyStrings_ptr&>>(x_ptr), cpp11::as_cpp<cpp11::decay_t<const cpp11::list_of<cpp11::strings> &>>(recodes)));
  END_CPP11
}
// r_sub.cpp
TinyStrings_ptr rcpp_sub(const TinyStrings_ptr& x_ptr, const long long start, const long long end);
extern "C" SEXP _tinystring_rcpp_sub(SEXP x_ptr, SEXP start, SEXP end) {
  BEGIN_CPP11
    return cpp11::as_sexp(rcpp_sub(cpp11::as_cpp<cpp11::decay_t<const TinyStrings_ptr&>>(x_ptr), cpp11::as_cpp<cpp11::decay_t<const long long>>(start), cpp11::as_cpp<cpp11::decay_t<const long long>>(end)));
  END_CPP11
}
// r_unpack.cpp
cpp11::writable::strings rcpp_unpack(const TinyStrings_ptr& x_ptr);
extern "C" SEXP _tinystring_rcpp_unpack(SEXP x_ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(rcpp_unpack(cpp11::as_cpp<cpp11::decay_t<const TinyStrings_ptr&>>(x_ptr)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_tinystring_rcpp_alphabet",    (DL_FUNC) &_tinystring_rcpp_alphabet,    1},
    {"_tinystring_rcpp_flatten",     (DL_FUNC) &_tinystring_rcpp_flatten,     2},
    {"_tinystring_rcpp_ip_recode",   (DL_FUNC) &_tinystring_rcpp_ip_recode,   2},
    {"_tinystring_rcpp_length",      (DL_FUNC) &_tinystring_rcpp_length,      1},
    {"_tinystring_rcpp_num_strings", (DL_FUNC) &_tinystring_rcpp_num_strings, 1},
    {"_tinystring_rcpp_pack",        (DL_FUNC) &_tinystring_rcpp_pack,        2},
    {"_tinystring_rcpp_recode",      (DL_FUNC) &_tinystring_rcpp_recode,      2},
    {"_tinystring_rcpp_set_length",  (DL_FUNC) &_tinystring_rcpp_set_length,  2},
    {"_tinystring_rcpp_sub",         (DL_FUNC) &_tinystring_rcpp_sub,         3},
    {"_tinystring_rcpp_unpack",      (DL_FUNC) &_tinystring_rcpp_unpack,      1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_tinystring(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
