# Generated by cpp11: do not edit by hand

rcpp_alphabet <- function(letters) {
  .Call(`_tinystring_rcpp_alphabet`, letters)
}

rcpp_get_alph_size <- function(x) {
  .Call(`_tinystring_rcpp_get_alph_size`, x)
}

rcpp_vpack <- function(x) {
  .Call(`_tinystring_rcpp_vpack`, x)
}

rcpp_vunpack <- function(x) {
  .Call(`_tinystring_rcpp_vunpack`, x)
}

rcpp_append_a <- function(x) {
  .Call(`_tinystring_rcpp_append_a`, x)
}
