# Generated by cpp11: do not edit by hand

rcpp_pack <- function(x, alphabet) {
  .Call(`_tinystring_rcpp_pack`, x, alphabet)
}

rcpp_display <- function(x) {
  .Call(`_tinystring_rcpp_display`, x)
}

rcpp_alphabet <- function(letters) {
  .Call(`_tinystring_rcpp_alphabet`, letters)
}

rcpp_get_alph_size <- function(x) {
  .Call(`_tinystring_rcpp_get_alph_size`, x)
}
