# Generated by cpp11: do not edit by hand

foo <- function() {
  .Call(`_tinystring_foo`)
}

baz <- function(a) {
  .Call(`_tinystring_baz`, a)
}

bar <- function(a_pointer) {
  .Call(`_tinystring_bar`, a_pointer)
}

rcpp_vpack <- function(x) {
  .Call(`_tinystring_rcpp_vpack`, x)
}

rcpp_vunpack <- function(x) {
  .Call(`_tinystring_rcpp_vunpack`, x)
}

rcpp_append_a <- function(x) {
  .Call(`_tinystring_rcpp_append_a`, x)
}
